 WRITE_SOB_FRACTION: 
  PUSH(FP);
  MOV(FP, SP);
  PUSH(R1);
  PUSH(R2);
  PUSH(R3);
  MOV(R2, 0);
  MOV(R2, FPARG(0));
  PUSH(INDD(R2, 1));
  CALL(WRITE_INTEGER);
  DROP(1);
  PUSH('/');
  CALL(PUTCHAR);
  DROP(1);
  PUSH(INDD(R2, 2));
  CALL(WRITE_INTEGER);
  DROP(1);
  POP(R3);
  POP(R2);
  POP(R1);
WRITE_SOB_FRACTION_END:
  POP(FP);
  RETURN;